services:
  postgres:
    image: postgres:16
    container_name: homework_06_postgres
    environment:
      POSTGRES_DB: office_booking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - homework_06_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d office_booking"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: homework_06_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - homework_06_pgadmin:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  homework_06_pgdata:
  homework_06_pgadmin:
